feat: Added branch cache

diff --git a/scripts/commit-msg b/scripts/commit-msg
--- a/scripts/commit-msg
+++ b/scripts/commit-msg
@@ -5,4 +5,11 @@ exec </dev/tty
 
 eval "$0.exe $1"
 
-tr -d '\n' < $1 > temp.txt && mv temp.txt $1
+if [ $? -eq 0 ]
+then
+    tr -d '\n' < $1 > temp.txt && mv temp.txt $1
+    exit 0
+else
+    echo "Hook failed. Commit is cancelled"
+    exit 1
+fi
